### ISSUE TITLE
TS files not converting to JS

### ISSUE THREAD

**Issue by talmog** [klaygomes/karma-typescript-preprocessor2#1]
Hi,
I have an angular2 project and I am trying to use you preprocessor to test my code.
The .ts files are being watched, so the tests are being rerun, but no new .js files are being generated, so the same tests are being run again.
What am I missing?
Thank you!

**Comment by klaygomes** [comment]
Hi @talmog, I'm sorry for delay. I'm assuming you are runnig into caching issues. A easy way to resolve that is altering option `transformPath`  to something like:

  transformPath: function(path) { 
        return path.replace(/.ts$/, '.js?'+ new Date);
      }

If you are running your tests using chrome, try to disable cache.
