### ISSUE TITLE
Update runs no test.

### ISSUE THREAD

**Issue by wawyed** [klaygomes/karma-typescript-preprocessor2#5]
I've updated from 1.1.0 to 1.2.0 and now none of my test seems to run. When I look at a ts file in chrome running karma it's empty with a comment saying that the file hasn't been compiled. Has any of the configuration changed?

**Comment by klaygomes** [comment]
Hello @wawyed, I just merged a little fix made by @lelandmiller, which SO are you using? (windows, linux, osx?)

**Comment by wawyed** [comment]
Windows.

**Comment by klaygomes** [comment]
ok, one minute. I will try to figure out what is going on

**Comment by klaygomes** [comment]
Please update to version 1.2.1.
