### ISSUE TITLE
Cannot find karma functions

### ISSUE THREAD

**Issue by pexak** [klaygomes/karma-typescript-preprocessor2#8]
I'v just copied your configuration and this what I'v got, any hints how to fix it?

```
tests/test.ts(3,1): error TS2304: Cannot find name 'describe'.
tests/test.ts(4,3): error TS2304: Cannot find name 'it'.
tests/test.ts(5,5): error TS2304: Cannot find name 'expect'.

```

**Comment by klaygomes** [comment]
Thanks for pointing it out. These files was not meant to be in this branch. I removed all .ts related files from master branch.

**Comment by pexak** [comment]
:+1:
